#!/bin/bash
# this script sucks I'm sorry

rm -r out
mkdir out

sass -t compressed --sourcemap=none src/smoothie.scss out/Smoothie.css

if [ $? == 0 ]
then
	echo "Theme exported to CSS successfully to out/Smoothie.css."
else
	echo -e "\e[31mSomething went wrong! Extra details in out/Smoothie.css."
fi